on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer
        run: ./.github/workflows/install_reindexer_macos.sh
        shell: bash
      - name: Build PyReindexer
        run: CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/include/reindexer LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib python3 setup.py sdist bdist_wheel
        shell: bash
      - name: Deploy PyReindexer To Pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install twine
          python3 -m twine upload --verbose dist/* -u __token__ -p pypi-$PYPI_TOKEN
          # wait for deploy finnishing on test pypi server
          sleep 240
        shell: bash

  test-macos:
    runs-on: macos-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer
        run: ./.github/workflows/install_reindexer_macos.sh
        shell: bash
      - name: Install PyReindexer
        run: LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib python3 -m pip install -vvv pyreindexer
        shell: bash
      - name: Test
        run: |
          cd /usr/local/lib/python3.9/site-packages/pyreindexer
          python3 example/main.py
          python3 -m unittest tests/test_builtin.py
          reindexer_server --db /tmp/reindex_test -l0 --serverlog="" --corelog="" --httplog="" --rpclog="" &
          server_pid=$!
          sleep 1
          python3 -m unittest tests/test_cproto.py
          kill $server_pid
          wait $server_pid
        shell: bash

  test-ubuntu20:
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer-Dev
        run: ./.github/workflows/install_reindexer_dev_ubuntu_focal.sh
        shell: bash
      - name: Install PyReindexer
        run: python3 -m pip install -vvv pyreindexer
        shell: bash
      - name: Install Reindexer-Server
        run: ./.github/workflows/install_reindexer_server_ubuntu_focal.sh
        shell: bash
      - name: Test
        run: |
          cd $(python3 -m site --user-site)/pyreindexer
          python3 example/main.py
          python3 -m unittest tests/test_builtin.py
          reindexer_server --db /tmp/reindex_test -l0 --serverlog="" --corelog="" --httplog="" --rpclog="" &
          server_pid=$!
          sleep 1
          python3 -m unittest tests/test_cproto.py
          kill $server_pid
          wait $server_pid
        shell: bash

  test-ubuntu18:
    runs-on: ubuntu-18.04
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer-Dev
        run: ./.github/workflows/install_reindexer_dev_ubuntu_bionic.sh
        shell: bash
      - name: Install PyReindexer
        run: |
          python3 -m pip install setuptools
          python3 -m pip install -vvv pyreindexer
        shell: bash
      - name: Install Reindexer-Server
        run: ./.github/workflows/install_reindexer_server_ubuntu_bionic.sh
        shell: bash
      - name: Test
        run: |
          cd $(python3 -m site --user-site)/pyreindexer
          python3 example/main.py
          python3 -m unittest tests/test_builtin.py
          reindexer_server --db /tmp/reindex_test -l0 --serverlog="" --corelog="" --httplog="" --rpclog="" &
          server_pid=$!
          sleep 1
          python3 -m unittest tests/test_cproto.py
          kill $server_pid
          wait $server_pid
        shell: bash
