on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer
        run: ./.github/workflows/install_reindexer.sh
        shell: bash
