on: push
jobs:
  deploy:
    runs-on: macos-11.0
    steps:
      - name: Install Reindexer
      - run: |
        filelist=$(wget -q -O - http://repo.reindexer.org/brew-bottles/ | grep "reindexer-" | sed "/.*>\(reindexer-.*\)<.*/s//\1/")
        ver1=0
        ver2=0
        ver3=0
        for x in $filelist
        do
            v1=$(echo $x | sed "/[^0-9]*\([0-9]*\)\..*/s//\1/")
            v2=$(echo $x | sed "/[^\.]*\.\([0-9]*\)\..*/s//\1/")
            v3=$(echo $x | sed "/[^\.]*\.[0-9]*\.\([0-9]\)\..*/s//\1/")
            if [[ $v1 -gt $ver1 || ( $v1 -eq $ver1 && ( $v2 -gt $ver2 || ( $v2 -eq $ver2 && $v3 -gt $ver3 ) ) ) ]]
            then
                ver1=$v1
                ver2=$v2
                ver3=$v3
                filename=$x
            fi
        done
        wget -O $filename http://repo.reindexer.org/brew-bottles/$filename
        brew install $filename
