on: push
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Install Reindexer
        run: |
          brew tap restream/reindexer
          brew install reindexer
        shell: bash
      - uses: actions/checkout@v2
      - name: Build PyReindexer
        run: |
          LIBRARY_PATH=$LIBRARY_PATH:/usr/local/Cellar/leveldb/1.23/lib:/usr/local/Cellar/snappy/1.1.9/lib python3 setup.py install #TODO remove LIBRARY_PATH
        shell: bash
      - name: Test
        run: |
          cd pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
        shell: bash

  test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{matrix.os}}
    env:
      OS: ${{matrix.os}}
    steps:
      - name: Install Reindexer-Dev
        run: |
          curl http://repo.reindexer.org/RX-KEY.GPG | sudo apt-key add
          if [[ $OS == ubuntu-20.04 ]]; then
            echo 'deb http://repo.reindexer.org/ubuntu-focal /' | sudo tee -a /etc/apt/sources.list
          else
            echo 'deb http://repo.reindexer.org/ubuntu-bionic /' | sudo tee -a /etc/apt/sources.list
          fi
          sudo apt-get update
          sudo apt-get install reindexer-dev
        shell: bash
      - uses: actions/checkout@v2
      - name: Build PyReindexer
        run: |
          python3 -m pip install setuptools
          python3 setup.py build
          sudo python3 setup.py install
        shell: bash
      - name: Install Reindexer-Server
        run: sudo apt-get install reindexer-server
        shell: bash
      - name: Test
        run: |
          cd pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
        shell: bash
