on: 
  push:
    branches-ignore:
      - master
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Install Reindexer
        run: |
          brew update
          brew install python3 || : # python doesn't need to be linked
          brew tap restream/reindexer
          brew install reindexer
        shell: bash
      - uses: actions/checkout@v3
      - name: Python Dependencies
        run: |
          pip install setuptools
      - name: Build PyReindexer
        run:
          python3 setup.py install
        shell: bash
      - name: Test
        run: |
          cd pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
        shell: bash

  test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04,ubuntu-22.04]
      fail-fast: false
    runs-on: ${{matrix.os}}
    env:
      OS: ${{matrix.os}}
    steps:
      - name: Install Reindexer-Dev
        run: |
          curl https://repo.reindexer.io/RX-KEY.GPG | sudo apt-key add
          if [[ $OS == ubuntu-20.04 ]]; then
            echo 'deb https://repo.reindexer.io/ubuntu-focal /' | sudo tee -a /etc/apt/sources.list
          else
            echo 'deb https://repo.reindexer.io/ubuntu-jammy /' | sudo tee -a /etc/apt/sources.list
          fi
          sudo apt-get update -y
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y reindexer-dev
        shell: bash
      - uses: actions/checkout@v3
      - name: Build PyReindexer
        run: |
          python3 -m pip install setuptools
          python3 setup.py build
          sudo python3 setup.py install
        shell: bash
      - name: Install Reindexer-Server
        run: sudo apt-get install reindexer-server
        shell: bash
      - name: Test
        run: |
          cd pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
        shell: bash
