name: Test the project
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-22.04
        - ubuntu-24.04
        #- macos-14
    runs-on: ${{matrix.os}}
    env:
      # Python 3.12 issue found on MasOS arm64 (darwin) runners, actions/setup-python@v5 incorrect venv setup
      BUILD_PYTHON_VERSION: ${{ startsWith(matrix.os, 'macos') && '3.8' || '3.12' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout PyReindexer repo
        uses: actions/checkout@v4
      - name: Install Reindexer-Dev\Server (MacOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew tap restream/reindexer
          brew install reindexer
      - name: Install Reindexer-Dev\Server (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          curl https://repo.reindexer.io/RX-KEY.GPG | sudo apt-key add
          if [[ ${{matrix.os}} == ubuntu-22.04 ]]; then
            echo 'deb https://repo.reindexer.io/ubuntu-jammy /' | sudo tee -a /etc/apt/sources.list
          elif [[ ${{matrix.os}} == ubuntu-24.04 ]]; then
            echo 'deb https://repo.reindexer.io/ubuntu-noble /' | sudo tee -a /etc/apt/sources.list
          else
            echo "${{matrix.os}} not supported"
            exit 1
          fi
          sudo apt-get update -y
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y reindexer-dev
          sudo apt-get install -y reindexer-server
      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip setuptools build
      - name: Prepare Test Environment
        run: python -m pip install -r requirements.txt
      - name: Build PyReindexer
        run: |
          python -m build
          python -m pip install .
      - name: Test
        run: |
          cd pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
