on:
  pull_request:
    types: [opened, reopened]
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Install Reindexer
        run: |
          brew tap restream/reindexer
          brew install reindexer
        shell: bash
      - uses: actions/checkout@v3
      - name: Build PyReindexer
        run: python3 setup.py sdist bdist_wheel
        shell: bash
      - name: Deploy PyReindexer To Test-Pypi
        env:
          TESTPYPI_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
        run: |
          python3 -m pip install twine
          python3 -m twine upload --verbose --repository testpypi dist/* -u __token__ -p pypi-$TESTPYPI_TOKEN
          # wait for deploy finnishing on test pypi server
          sleep 240
        shell: bash

  test-macos:
    runs-on: macos-latest
    needs: deploy
    steps:
      - name: Install Reindexer
        run: |
          brew tap restream/reindexer
          brew install reindexer
        shell: bash
      - uses: actions/checkout@v3
      - name: Install PyReindexer
        run: python3 -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps pyreindexer
        shell: bash
      - name: Prepare Test Environment
        run: python3 -m pip install pytest==6.2.5 delegator envoy pyhamcrest=2.0.2
        shell: bash
      - name: Test
        run: |
          cd $(python3 -m site --user-site)/pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
        shell: bash

  test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
      fail-fast: false
    runs-on: ${{matrix.os}}
    env:
      OS: ${{matrix.os}}
    needs: deploy
    steps:
      - name: Install Reindexer-Dev
        run: |
          curl https://repo.reindexer.io/RX-KEY.GPG | sudo apt-key add
          if [[ $OS == ubuntu-20.04 ]]; then
            echo 'deb https://repo.reindexer.io/ubuntu-focal /' | sudo tee -a /etc/apt/sources.list
          else
            echo 'deb https://repo.reindexer.io/ubuntu-bionic /' | sudo tee -a /etc/apt/sources.list
          fi
          sudo apt-get update
          sudo apt-get install reindexer-dev
        shell: bash
      - uses: actions/checkout@v3
      - name: Install PyReindexer
        run: |
          python3 -m pip install setuptools
          python3 -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps pyreindexer
        shell: bash
      - name: Install Reindexer-Server
        run: sudo apt-get install reindexer-server
        shell: bash
      - name: Prepare Test Environment
        run: python3 -m pip install pytest==6.2.5 delegator envoy pyhamcrest=2.0.2
        shell: bash
      - name: Test
        run: |
          cd $(python3 -m site --user-site)/pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
        shell: bash
