name: Upload Release package to TestPyPI
#on:
#  pull_request:
#    types: [opened, reopened]
on:
  push:
    branches-ignore:
      - master

#jobs:
#  build:
#    name: Build wheels on ${{ matrix.platform }}
#    runs-on: ${{ matrix.platform }}
#    strategy:
#      matrix:
#        platform: [ macos-14 ]
#    env:
#      DEPLOY_BUILD_PYTHON_VERSION: "3.11"
#      MACOSX_DEPLOYMENT_TARGET: "14"
#      CIBW_BUILD: "cp311-*"
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - name: Checkout PyReindexer repo
#        uses: actions/checkout@v4
#      - name: Set up Python ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
#      - name: Install Python dependencies
#        run: python -m pip install --upgrade pip build cibuildwheel
#      - name: Build PyReindexer wheels
#        run: python -m cibuildwheel --output-dir wheels
#      - name: Install PyReindexer
#        run: |
#          python -m pip install --upgrade --disable-pip-version-check pip importlib_metadata
#          python -m pip install wheels/*whl --no-deps pyreindexer
#      - name: Prepare Test Environment
#        run: python -m pip install -r requirements.txt
#      - name: Store all build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: rx_artifacts
#          path: |
#            dist/*
#            wheels/*whl
#      - name: Test builtin
#        run: |
#          cd $(python -c "import sysconfig; print(sysconfig.get_path('purelib'))")/pyreindexer
#          $GITHUB_WORKSPACE/.github/workflows/test.sh builtin

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: macos-14
            python: "3.9"
            py_cp: 39
          - platform: macos-14
            python: "3.13"
            py_cp: 313
    env:
      DEPLOY_BUILD_PYTHON_VERSION: ${{ matrix.python }}
      MACOSX_DEPLOYMENT_TARGET: "14"
      CIBW_BUILD: "cp${{ matrix.py_cp }}-*" # build wheel for python 3.9 and 3.13
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout PyReindexer repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip cibuildwheel
      - name: Build PyReindexer wheels
        run: python -m cibuildwheel --output-dir dist
      - name: Store all build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rx_artifacts_wheels
          path: dist/*

  build_sdist:
    name: Build sdist on macos-14
    runs-on: macos-14
    env:
      DEPLOY_BUILD_PYTHON_VERSION: "3.12"
      MACOSX_DEPLOYMENT_TARGET: "14"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout PyReindexer repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEPLOY_BUILD_PYTHON_VERSION }}
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip build
      - name: Build PyReindexer dist
        run: python -m build --sdist
      - name: Store all build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rx_artifacts_sdist
          path: dist/*

  deploy:
    name: Upload to TestPyPI (ubuntu)
    runs-on: ubuntu-22.04
    needs: [ build_wheels, build_sdist ]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyreindexer/
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: rx_artifacts*
          path: dist
          merge-multiple: true
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          # user: __token__ ## used as default
          password: pypi-${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          attestations: false

  #  test_dist:
  #    strategy:
  #      fail-fast: false
  #      matrix:
  #        platform: [ macos-14 ]
  #        python: [ "3.12", "3.13" ] # versions of python with missing wheel and presented wheel
  #    runs-on: ${{ matrix.platform }}
  #    needs: deploy
  #    defaults:
  #      run:
  #        shell: bash
  #    steps:
  #      - name: Checkout PyReindexer
  #        uses: actions/checkout@v4
  #      - name: Install Reindexer (MacOS)
  #        run: |
  #          brew tap restream/reindexer
  #          brew install reindexer
  #      - name: Set up Python ${{ matrix.python }}
  #        uses: actions/setup-python@v5
  #        env:
  #          PIP_DISABLE_PIP_VERSION_CHECK: 1
  #        with:
  #          python-version: ${{ matrix.python }}
  #      - name: Install PyReindexer
  #        run: |
  #          python -m pip install --upgrade --disable-pip-version-check pip importlib_metadata setuptools wheel
  #          if [[ ${{matrix.python}} == "3.13" ]]; then
  #            # presented wheel needs `no-binary` for the forced sdist install
  #            python -m pip install -vvv --no-deps --no-build-isolation --no-binary pyreindexer --index-url https://test.pypi.org/simple/ pyreindexer
  #          else
  #            python -m pip install -vvv --no-deps --no-build-isolation --index-url https://test.pypi.org/simple/ pyreindexer
  #          fi
  #      - name: Prepare Test Environment
  #        run: python -m pip install -r requirements.txt
  #      - name: Test
  #        run: |
  #          cd $(python -c "import sysconfig; print(sysconfig.get_path('purelib'))")/pyreindexer
  #          $GITHUB_WORKSPACE/.github/workflows/test.sh

  test_wheel:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.9", "3.13" ] # both versions of python with the wheel presented
        rxmode: [ builtin, cproto ]
    needs: deploy
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout PyReindexer
        uses: actions/checkout@v4
      - name: Install Reindexer (MacOS)
        if: matrix.rxmode == 'cproto'
        run: |
          brew tap restream/reindexer
          brew install reindexer
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        with:
          python-version: ${{ matrix.python }}
      - name: Install PyReindexer
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip importlib_metadata
          python -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps pyreindexer
      - name: Prepare Test Environment
        run: python -m pip install -r requirements.txt
      - name: Test ${{ matrix.rxmode }}
        run: |
          cd $(python -c "import sysconfig; print(sysconfig.get_path('purelib'))")/pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh ${{matrix.rxmode}}