on: push
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer
        run: ./.github/workflows/install_reindexer_macos.sh
        shell: bash
      - name: Build PyReindexer
        run: CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/include/reindexer LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib python3 setup.py install
        shell: bash
      - name: Test
        run: |
          python3 pyreindexer/example/main.py
          python3 -m unittest pyreindexer/tests/test_builtin.py
          reindexer_server --db /tmp/reindex_test -l0 --serverlog="" --corelog="" --httplog="" --rpclog="" &
          server_pid=$!
          sleep 1
          python3 -m unittest pyreindexer/tests/test_cproto.py
          kill $server_pid
          wait $server_pid
        shell: bash

  test-ubuntu20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer-Dev
        run: ./.github/workflows/install_reindexer_dev_ubuntu_focal.sh
        shell: bash
      - name: Build PyReindexer
        run: sudo python3 setup.py install
        shell: bash
      - name: Install Reindexer-Server
        run: ./.github/workflows/install_reindexer_server_ubuntu_focal.sh
        shell: bash
      - name: Test
        run: |
          python3 pyreindexer/example/main.py
          python3 -m unittest pyreindexer/tests/test_builtin.py
          reindexer_server --db /tmp/reindex_test -l0 --serverlog="" --corelog="" --httplog="" --rpclog="" &
          server_pid=$!
          sleep 1
          python3 -m unittest pyreindexer/tests/test_cproto.py
          kill $server_pid
          wait $server_pid
        shell: bash

  test-ubuntu18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer-Dev
        run: ./.github/workflows/install_reindexer_dev_ubuntu_bionic.sh
        shell: bash
      - name: Build PyReindexer
        run: sudo python3 setup.py install
        shell: bash
      - name: Install Reindexer-Server
        run: ./.github/workflows/install_reindexer_server_ubuntu_bionic.sh
        shell: bash
      - name: Test
        run: |
          python3 pyreindexer/example/main.py
          python3 -m unittest pyreindexer/tests/test_builtin.py
          reindexer_server --db /tmp/reindex_test -l0 --serverlog="" --corelog="" --httplog="" --rpclog="" &
          server_pid=$!
          sleep 1
          python3 -m unittest pyreindexer/tests/test_cproto.py
          kill $server_pid
          wait $server_pid
        shell: bash
