on:
  workflow_dispatch:
    inputs:
      rx_commit:
        required: true
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Clone Reindexer
        env:
          RX_COMMIT: ${{ github.event.inputs.rx_commit }}
          RX_DIR: rx_build
        run: |
          mkdir $RX_DIR
          git clone https://github.com/restream/reindexer.git $RX_DIR
          cd $RX_DIR
          git checkout $RX_COMMIT
      - uses: actions/checkout@v2
