on: push
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer
        run: ./.github/workflows/install_reindexer_macos.sh
        shell: bash
      - name: Test
        run: ./.github/workflows/test_pyreindexer.sh
        shell: bash

  test-ubuntu20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer-Dev
        run: ./.github/workflows/install_reindexer_dev_ubuntu_focal.sh
        shell: bash
      - name: Install Reindexer-Server
        run: ./.github/workflows/install_reindexer_server_ubuntu_focal.sh
        shell: bash
      - name: Test
        run: ./.github/workflows/test_pyreindexer.sh
        shell: bash

  test-ubuntu18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Reindexer-Dev
        run: ./.github/workflows/install_reindexer_dev_ubuntu_bionic.sh
        shell: bash
      - name: Install Reindexer-Server
        run: ./.github/workflows/install_reindexer_server_ubuntu_bionic.sh
        shell: bash
      - name: Test
        run: ./.github/workflows/test_pyreindexer.sh
        shell: bash
