on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Install Reindexer
        run: |
          ls
          pwd
          ./.github/workflows/install_reindexer.sh
        shell: bash
