on:
  workflow_dispatch:
    inputs:
      rx_commit:
        required: true
        default: ''
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $rx_commit
