name: Test the project
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.9", "3.13" ]
        platform: [ ubuntu-22.04, ubuntu-24.04, macos-14, macos-15 ]
        include:
          - python: "3.8"
            platform: ubuntu-22.04
            distutils: stdlib
          - python: "3.10"
            platform: ubuntu-24.04
          - python: "3.11"
            platform: ubuntu-24.04
          - python: "3.12"
            platform: ubuntu-24.04
    runs-on: ${{ matrix.platform }}
    env:
      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils || 'local' }}
      MACOSX_DEPLOYMENT_TARGET: "14"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout PyReindexer repo
        uses: actions/checkout@v4
      - name: Install Reindexer-Dev\Server (MacOS)
        if: startsWith(matrix.platform, 'macos')
        run: |
          brew uninstall cmake
          brew tap restream/reindexer
          brew install reindexer
      - name: Install Reindexer-Dev\Server (Ubuntu)
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          curl https://repo.reindexer.io/RX-KEY.GPG | sudo apt-key add
          if [[ ${{matrix.platform}} == ubuntu-22.04 ]]; then
            echo 'deb https://repo.reindexer.io/ubuntu-jammy /' | sudo tee -a /etc/apt/sources.list
          elif [[ ${{matrix.platform}} == ubuntu-24.04 ]]; then
            echo 'deb https://repo.reindexer.io/ubuntu-noble /' | sudo tee -a /etc/apt/sources.list
          else
            echo "${{matrix.platform}} not supported"
            exit 1
          fi
          sudo apt-get update -y
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y reindexer-dev
          sudo apt-get install -y reindexer-server
      - name: Set up Python ${{ matrix.python }}
        id: python-install
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: false
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
          # Workaround for actions/setup-python#981 (env var only modified for this specific step)
          SETUPTOOLS_USE_DISTUTILS: >-
            ${{ matrix.platform == 'macos-14' && matrix.python == '3.9' && 'stdlib' || 'local' }}-
            ${{ matrix.platform == 'macos-15' && matrix.python == '3.9' && 'stdlib' || 'local' }}-
            ${{ matrix.platform == 'macos-latest' && matrix.python == '3.9' && 'stdlib' || 'local' }}-
            ${{ matrix.platform == 'ubuntu-22.04' && matrix.python == '3.8' && 'stdlib' || 'local' }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip setuptools build
      - name: Prepare Test Environment
        run: python -m pip install -r requirements.txt
      - name: Build PyReindexer
        run: |
          python -m build
          python -m pip install .
      - name: Test
        run: |
          cd pyreindexer
          $GITHUB_WORKSPACE/.github/workflows/test.sh
      - name: Store test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test_artif
          path: tests/logs